### ISSUE TITLE
weird error message in Python

### ISSUE THREAD

**Issue by ahmetb** [buildpack/lifecycle#136] opened 2019-05-29 00:02 UTC
I get an undebuggable `[builder] Error: failed to : exit status 100` while building a very simple Python app with `heroku/buildpacks` stack.

The app I'm using is https://github.com/knative/docs/tree/dee2bd07515f81179ff81715f4499807c9e2d79e/docs/serving/samples/hello-world/helloworld-python

I deleted dockerfile and added a requirements.txt containing

```
Flask
gunicorn
```

and Procfile:

    web: exec gunicorn --bind :$PORT --workers 1 --threads 8 app:app

```
$ pack build gcr.io/ahmetb-samples-playground/helloworld-python:pack --builder heroku/buildpacks
Pulling image index.docker.io/heroku/buildpacks:latest
latest: Pulling from heroku/buildpacks
Digest: sha256:9f86541d462ca1d812028104566c6a47e37445a27ad55f729b0182a6614c1085
Status: Image is up to date for heroku/buildpacks:latest
Selected run image heroku/pack:18 from builder
Pulling image heroku/pack:18
18: Pulling from heroku/pack
Digest: sha256:2230feb0c968f556fc2bca711595fda6355cd2a8c19ecb4d5b483abc30e51c3a
Status: Image is up to date for heroku/pack:18
Using build cache image pack-cache-60844030afda
Warning: lifecycle version unknown
===> DETECTING
[detector] Trying group of 2...
[detector] ======== Output: Ruby ========
[detector] no
[detector] ======== Results ========
[detector] Ruby: error (1)
[detector] Procfile: pass
[detector] Trying group of 2...
[detector] ======== Results ========
[detector] Python: pass
[detector] Procfile: pass
===> RESTORING
[restorer] cache image 'pack-cache-60844030afda' not found, nothing to restore
===> ANALYZING
[analyzer] WARNING: image 'gcr.io/ahmetb-samples-playground/helloworld-python:pack' not found or requires authentication to access
[analyzer] WARNING: image 'gcr.io/ahmetb-samples-playground/helloworld-python:pack' has incompatible 'io.buildpacks.lifecycle.metadata' label
===> BUILDING
[builder] -----> Installing python-3.6.8
[builder] -----> Installing pip
[builder] -----> Installing SQLite3
[builder] Error: failed to : exit status 100
```

**Comment by jamesward** [comment] 2019-06-05 15:08
I wasn't able to reproduce this but I did have to fix the `Procfile` to get it working:
```
web: gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 app:app
```

Here is my fork:
https://github.com/jamesward/knative-docs/tree/master/docs/serving/samples/hello-world/helloworld-python

I ran:
```
pack build hellworld-python --builder heroku/buildpacks
```

Then:
```
docker run -p8000:8000 -ePORT=8000 hellworld-python
```

**Comment by ekcasey** [comment] 2019-07-03 15:17
@ahmetb Other than the abstruse error message this doesn't seem like a lifecycle issue to me. 

The newest version of the `heroku/buildpacks` builder appears to contain lifecycle version `v0.2.0` 
```
$ pack inspect-builder heroku/buildpacks
Inspecting builder: heroku/buildpacks

Remote
------

Stack: heroku-18

Lifecycle Version: 0.2.0
...
```
This lifecycle version should produce slightly clearer error messages (https://github.com/buildpack/lifecycle/pull/135). Are you still seeing this issues with the latest `heroku/buildpacks` builders?

**Comment by ahmetb** [comment] 2019-07-03 18:22
I am not sure where to report this issue. 
It’s very unclear where the heroku/buildpacks image comes from. So far I haven’t been able to find it.

**Comment by sclevine** [comment] 2019-07-03 18:28
@hone or @jkutner may be able to direct your question to the right place :)

**Comment by jkutner** [comment] 2019-07-05 12:54
@ahmetb I'm pretty sure this was due to a bug in the Python buildpack that was recently fixed. If you run `docker pull heroku/buildpacks:18` and try again, I think you'll find that it works. Sorry about that.

**Comment by jamesward** [comment] 2019-07-06 20:22
I think the thing that Lifecycle could do is provide more details on what to do when errors occur. If there is a failure in the buildpack, point the user to the bug db for the buildpack. If something else goes wrong, maybe point them to the bug db for the builder?

**Comment by ahmetb** [comment] 2019-07-10 05:02
I think the root problem here is that as a developer I spent an hour and:

1. I could not get any more verbose output from this toolchain
2. I could not find the source code of heroku buildpacks image from Docker Hub or anywhere else to debug more.

Fundamentally, this toolchain is not currently establishing trust on my side. When something like this blocks me, I should be at least able to open a bug report somewhere easily.

**Comment by sclevine** [comment] 2019-07-10 05:33
In cases like these, the lifecycle provided by this project doesn't have any additional information that could be useful to the user.

We could insist that all valid builders or buildpacks provide the lifecycle with metadata describing their origin and authorship, but in this case, the buildpack has all of the information about the failure and is much better equipped to direct you to the appropriate place.

Additionally, the v3 buildpack API is still in beta. It may take some time before all v3 buildpack authors have documented their new / converted buildpacks. Some builders may have more information published about them than others.

**Comment by jkutner** [comment] 2019-09-07 19:57
This was a bug in the python buildpack fixed in https://github.com/heroku/heroku-buildpack-python/issues/696

The lack of a "verbose" logging mode is captured in https://github.com/buildpack/pack/issues/271

**Closed by jkutner** 2019-09-07 19:57 UTC
